name: stockcheck
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - freetype=2.9.1=hb4e5f40_0
  - jpeg=9b=he5867d9_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.0.10=hcb84e12_2
  - zstd=1.3.7=h5bba6e5_0
  - altgraph=0.16.1=py_0
  - asn1crypto=0.24.0=py36_1003
  - beautifulsoup4=4.8.0=py36_0
  - cffi=1.12.3=py36hccf1714_0
  - chardet=3.0.4=py36_1003
  - cryptography=2.7=py36h212c5bf_0
  - idna=2.8=py36_1000
  - macholib=1.11=py_0
  - olefile=0.46=py_0
  - pip=19.2.1=py36_0
  - pycparser=2.19=py36_1
  - pycrypto=2.6.1=py36h1de35cc_1002
  - pyinstaller=3.4=py36ha92aebf_0
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.7.0=py36_0
  - requests=2.22.0=py36_1
  - selenium=3.141.0=py36h1de35cc_1000
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_1000
  - soupsieve=1.9.2=py36_0
  - urllib3=1.25.3=py36_0
  - wheel=0.33.4=py36_0
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_0
  - click=7.0=py36_0
  - flask=1.1.1=py_0
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10.1=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - markupsafe=1.1.1=py36h1de35cc_0
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1c=h1de35cc_1
  - pillow=6.1.0=py36hb68e598_0
  - python=3.6.8=haf84260_0
  - readline=7.0=h1de35cc_5
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.15.4=py_0
  - xz=5.2.4=h1de35cc_4
  - yapf=0.27.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/johnamadeodaniswara/anaconda/envs/stockcheck

